spring.application.name=consultation-service
server.port=${PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:5}

server.compression.enabled=true
server.compression.mime-types=application/json,application/javascript,text/html,text/css,text/plain
server.compression.min-response-size=1024

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

ufb.jwt.secret=${UFB_JWT_SECRET}

spring.rabbitmq.addresses=${RABBITMQ_URL}
